### ISSUE TITLE
My Themes and Plugins get pruned despite [local] prefix

### ISSUE THREAD

**Issue by milojennings** [visiblevc/wordpress-starter#102]
## Overview

- What's your problem about?
    - Local themes & plugins are pruned / deleted 
- What is your operating system?
    - Mac OSX Sierra 10.12.5
- What is your docker version? `docker version`
    - 17.03.1-ce

## Details

When I run `docker-compose up -d && docker-compose logs -f wordpress` the contents of `wp-content/themes/Divi` is deleted. The folder remains, but no files are left. It reports `Warning: Could not fully remove the theme Divi.`. 

I read through this [issue](https://github.com/visiblevc/wordpress-starter/issues/84) and followed the recommendations there. As you can see in my yml file, I've got it added to the theme list like so: `[local]Divi`

What am I missing?

## `docker-compose.yml`

```yml
version: '2'
services:
  wordpress:
    image: visiblevc/wordpress:latest
    ports:
      - 8080:80
    volumes:
      # database configuration
      - ./data:/data
      # development theme setup
      - ./wp-content/themes/Divi:/app/wp-content/themes/Divi
      # WordPress uploads folder
      - ./wp-content/uploads:/app/wp-content/uploads
    environment:
      DB_NAME: wordpress
      DB_PASS: root
      PLUGINS: >-
        wordpress-importer,
      THEMES: >-
        [local]Divi,
      WP_DEBUG: 'true'
  db:
    image: mariadb:10 # or mysql:5.7
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 22222:80
volumes:
  data:
```

## Project structure

```
/data
  /database.sql
/wp-content
  /themes
    /Divi
```

## `docker-compose up` output

```
wordpress_1   | ==> Checking themes
wordpress_1   | Warning: Could not fully remove the theme Divi.
wordpress_1   | Error: No themes deleted.
wordpress_1   | ==> Checking plugins
wordpress_1   | Success: Plugins already activated.
wordpress_1   | ==> Finalizing
```

**Comment by dsifford** [comment]
Hey @milojennings 

I think I might know what's going on. First, can you tell me what the output of the following command is?

```
$ docker image inspect visiblevc/wordpress -f '{{.ContainerConfig.Labels.version}}'
```

Thanks in advance 😄

**Comment by milojennings** [comment]
Hey @dsifford thanks for the quick response. The output of that command is:

```
0.15.0-php7.1
```

**Comment by dsifford** [comment]
Aha! Thought that might be the case.

Your image is one version outdated. The deletion issue was fixed (as far as I could tell) in 3db6fa04e93e5e037f4fab40e406b40ac9fe98fe

Deleting and re-pulling the image should do the trick. Let me know either way. Sorry for the headache!

**Comment by milojennings** [comment]
Well... It looks like I'm running version `0.15.1-php7.1` now, yet it's still deleting themes and plugins.

**Comment by dsifford** [comment]
Hm, dang.

Just to confirm. You completely destroyed your old volumes and containers and rebuilt fresh, correct?

I'll try and replicate this on my end to see if I can reproduce.

**Comment by dsifford** [comment]
@milojennings If you have a repo somewhere that I can pull, that would be awesome. I have access to the Divi theme so that doesn't need to be included.

**Comment by milojennings** [comment]
@dsifford I ran 
```docker rmi visiblevc/wordpress:latest --force``` 
then 
```docker-compose up -d && docker-compose logs -f wordpress```

Is there anything else I should have done? I'm pretty new to using Docker.

**Comment by dsifford** [comment]
Not sure if it would matter or not, but I was talking about doing `docker-compose down -v`

prior to re-running `docker-compose up`.

The goal would be to have both of the following commands show no results:

```
$ docker volume ls
$ docker ps -a
```

**Comment by dsifford** [comment]
@milojennings Just tried to reproduce using the following compose file and was not able to. Worked fine on my end.

I have a feeling mac handles groups differently than linux. I have a fix I think, but if you don't mind, could you try something for me first?

Create an empty directory somewhere on your computer and add a `docker-compose.yml` file in it as well as a text file with some text in it called `tester.txt`. In the docker-compose file, add the following:

```yaml
version: '3'
services:
  busy:
    image: busybox
    command: ping google.com
    volumes:
      - ./tester.txt:/tester.txt
volumes:
  data:
```

Then run the following sequence of lines and let me know what the output is:

```
$ docker-compose up -d
$ docker-compose exec busy /bin/sh
# stat -c '%n - User: %U(%u), Group: %G(%g)' tester.txt
```

Where `$` is in your own shell and `#` is executed in the `busy` container.
