### ISSUE TITLE
Storing Uploads of Wordpress

### ISSUE THREAD

**Issue by lukasholzer** [visiblevc/wordpress-starter#104]
Hey I have the problem, that everytime I restart my machine all the uploads are gone. They are still in the library but if I call the url I get a 404.

How should I configure the docker-compose.yml to provide access to a local folder. Can you help me?

## `docker-compose.yml`

```yml
version: '3'

services:

  wordpress:
    image: visiblevc/wordpress:latest
    ports:
      - "8080:80"
    restart: always
    links:
      - db:mysql
    volumes:
      - ./data:/data # If mysql database dump is as .sql file inside
      - ./theme:/app/wp-content/themes/robertholzer
      - ./config/plugins/advanced-custom-fields-pro:/app/wp-content/plugins/advanced-custom-fields-pro
environment:
      DB_NAME: robertholzer
      DB_HOST: db
      DB_PASS: root
      SERVER_NAME: localhost
      ADMIN_EMAIL: office@lukasholzer.com
      WP_DEBUG: 'true'
      WP_VERSION: latest
      PLUGINS: >-
        [local]advanced-custom-fields-pro,
        acf-image-crop-add-on,
        wordpress-importer,
        [soil]https://github.com/roots/soil/archive/3.7.1.zip,
      THEMES: >-
        [local]robertholzer

frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: frontend
    ports:
      - "4000:4000" # HMR Server
      - "3000:3000" # BrowserSync
      - "3001:3001" # BrwoserSync Admin interface
    volumes:
      # - ./theme/src:/opt/hmrserver/src
      - ./theme:/opt/hmrserver/theme

  composer:
    restart: 'no'
    image: composer/composer:alpine
    command: install
    volumes:
      - ./theme:/app


  imageservice:
    image: apsl/thumbor
    ports:
      - "5000:8000"
    volumes:
      - images:/data
    networks:
      - frontend
    environment:
      - ENGINE=graphicsmagick_engine.engine
      - ALLOW_UNSAFE_URL=True
      - AUTO_WEBP=True
      - PROGRESSIVE_JPEG=True

  db:
    image: mysql:5.7
    hostname: dbhost
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
    volumes:
      - data:/var/lib/mysql

volumes:
  data:
  images:
    driver: local


networks:
  frontend:
    driver: bridge
```

## Project structure

```
/config
  /plugins
  /acf
/data
/theme
```

**Comment by dsifford** [comment]
@lukasholzer Just add the uploads directory as a volume to your wordpress service

```yml
version: '3'
services:
  wordpress:
    volumes:
      - ./uploads:/app/wp-content/uploads
```
