### ISSUE TITLE
Maximum upload file size

### ISSUE THREAD

**Issue by lukasholzer** [visiblevc/wordpress-starter#105]
Hey is there a way to increase the Maximum upload file size of 2 MB for WordPress?.
The best way would be an environmental variable in the docker-compose.yml

Regards Lukas

**Comment by dsifford** [comment]
Yeah, just create a `.ini` file somewhere in your project, adjust the values of `memory_limit`, `post_max_size`, and `upload_max_filesize`, and then add it as a volume to `/usr/local/etc/php/conf.d/file-name-can-be-anything.ini`

**Comment by lukasholzer** [comment]
**./config/php.ini**
``` ini
memory_limit = 64M
post_max_size = 64M
upload_max_filesize = 64M
```

``` yml
…
wordpress:
    image: visiblevc/wordpress:latest
    ports:
      - "8080:80"
    restart: always
    links:
      - db:mysql
    volumes:
      - ./uploads:/app/wp-content/uploads
      - ./theme:/app/wp-content/themes/robertholzer
      - ./config/php.ini:/usr/local/etc/php/conf.d/php.ini
…
```

but wordpress tells me *'Maximum upload file size: 2 MB.'*
