### ISSUE TITLE
URL's don't work for an imported website

### ISSUE THREAD

**Issue by ieugen** [visiblevc/wordpress-starter#107]
## Overview

I started working on a project based on this starter. I imported an existing database and the home page is rendered when I go to `http://localhost:8080/ `. However, all the links in the homepage redirect me to `http://localhost/...` instead of `http://localhost:8080/...`  . Why is that happening? I have tried everything to fix this. 

How can I work on an imported wordpres database locally?

I'm using: 
Debian Stretch
Docker version 17.06.0-ce, build 02c1d87
docker-compose version 1.14.0, build c7bdf9e

## `docker-compose.yml`

```yml
version: '3'
services:
  wordpress:
    image: visiblevc/wordpress:0.15.2-php7.1
    ports:
      - 8080:80
      - 443:443
    volumes:
      - ./data:/data
      - ./wp-content/themes/example-2016:/app/wp-content/themes/example-2016
    environment:
      DB_NAME: example2017
      DB_PASS: root
      WP_DEBUG: "true"
      WP_DEBUG_LOG: "true"
      SEARCH_REPLACE: example.net,localhost:8080
      PLUGINS: >-
        academic-bloggers-toolkit,
        co-authors-plus,
        [WP-API]https://github.com/WP-API/WP-API/archive/master.zip,
  db:
    image: mariadb:10 # or mysql:5.7
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 22222:80
volumes:
  data:
```

## Project structure

```
/data
  /database.sql
/wp-content
  /themes
    /example-2016
```

Regards,
