### ISSUE TITLE
Multiple starter instances

### ISSUE THREAD

**Issue by Surgeonito** [visiblevc/wordpress-starter#113]
Hi,
this starter is a awesome tool.
Thanks.
Is it possible and - if so - how can I achieve it to run multiple WordPress projects at the same time with this wordpress-starter?
I assume that some sort of port settings need to be changed in docker-compose.yml, but have no clue how to achieve it.

**Comment by dsifford** [comment]
@Surgeonito Though theoretically possible by creating additional wordpress services and linking them to the database service (using a different database name), it would be safer to achieve this by creating a cluster of wordpress nodes and managing them with either kubernetes or docker swarm.

That said, if you're still determined to try this out in a development setting, I'm pretty sure you can do it the following way:

```yml
version: '3'
services:
  wordpress_1:
    image: visiblevc/wordpress:latest
    ports:
      - 8080:80
      - 443:443
    environment:
      DB_HOST: db
      DB_NAME: wordpress_1
      DB_PASS: root # must match below
  wordpress_2:
    image: visiblevc/wordpress:latest
    ports:
      - 8081:80
      - 443:443
    environment:
      DB_HOST: db
      DB_NAME: wordpress_2
      DB_PASS: root # must match below
  db:
    image: mysql:5.7 # or mariadb:10
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
volumes:
  data:
```
