### ISSUE TITLE
Cannot log in into wordpress with imported .sql file

### ISSUE THREAD

**Issue by lukasholzer** [visiblevc/wordpress-starter#122]
Hey, I have the Problem that I want to import a DB dump from the staging server with the actual data. Every thing is so fine I start it with `docker-compose up wordpress` and when I open the browser window on localhost:8080 I get a white screen (blank page) when I go to *localhost:8080/wp-admin* and log me in with my credentials, I get redirected to the admin interface of the staging server **sls-eventservice.ch**

**(notice: the staging server has a different wp_ prefix)**

What I am doing wrong? 

Regards Lukas

- Mac os high Sierra
- Docker version 17.09.0-ce-mac35

## `docker-compose.yml`

```yml
version: '3'

services:

  wordpress:
    image: visiblevc/wordpress:latest
    ports:
      - "8080:80"
    restart: always
    links:
      - db:mysql
    volumes:
      - ./data:/data # If mysql database dump is as .sql file inside
      - ./uploads:/app/wp-content/uploads
      - ./theme:/app/wp-content/themes/sls
      - ./config/tweaks.ini:/usr/local/etc/php/conf.d/tweaks.ini # Optional tweaks to the php.ini config

    environment:
      DB_NAME: u44750db1
      DB_HOST: db
      DB_PASS: ...
      DB_PREFIX: ghth_
      SERVER_NAME: localhost
      ADMIN_EMAIL: lukas.holzer@typeflow.cc
      WP_DEBUG: 'true'
      WP_VERSION: latest
      URL_REPLACE: www.sls-eventservice.ch, localhost:8080
      PLUGINS: >-
        [advanced-custom-fields-pro]https://github.com/wp-premium/advanced-custom-fields-pro/archive/5.6.2.zip,
        acf-to-rest-api,
        acf-image-crop-add-on,
        wordpress-importer,
        post-types-order,
        [soil]https://github.com/roots/soil/archive/3.7.1.zip,
      THEMES: >-
        [local]sls

  db:
    image: mysql:5.7
    hostname: dbhost
    environment:
      MYSQL_ROOT_PASSWORD: ...
      MYSQL_DATABASE: u44750db1
    volumes:
      - data:/var/lib/mysql

volumes:
  data:

```

## Project structure

```
/data
  /u44750db1.sql
/theme
  ...
/uploads
docker-compose.yml
```

## `docker-compose up wordpress` output

``` bash
Creating network "slseventservice_default" with the default driver
Creating slseventservice_db_1 ... 
Creating slseventservice_db_1 ... done
Creating slseventservice_wordpress_1 ... 
Creating slseventservice_wordpress_1 ... done
Attaching to slseventservice_wordpress_1
wordpress_1  | ===============================================================================
wordpress_1  |                          Begin WordPress Installation
wordpress_1  | ===============================================================================
wordpress_1  | ==> Installing WordPress
wordpress_1  |   -> Downloading... ✓
wordpress_1  | ==> Waiting for MySQL to initialize...
wordpress_1  |   ->  mysqld is alive
wordpress_1  | ==> Configuring WordPress
wordpress_1  |   -> Generating wp-config.php file... ✓
wordpress_1  | ==> Checking database
wordpress_1  |   -> Database exists. SKIPPING... 
wordpress_1  | ==> Checking for multisite
wordpress_1  |   -> Multisite not found. SKIPPING... 
wordpress_1  | ==> Checking themes
wordpress_1  |   -> (1/1) 'sls' listed as a local volume. SKIPPING... 
wordpress_1  | ==> Checking for orphaned themes
wordpress_1  |   -> 'twentyfifteen' no longer needed. Pruning ✓
wordpress_1  |   -> 'twentyseventeen' no longer needed. Pruning ✓
wordpress_1  |   -> 'twentysixteen' no longer needed. Pruning ✓
wordpress_1  | ==> Checking plugins
wordpress_1  |   -> (1/6) 'advanced-custom-fields-pro' not found. Installing... ✓
wordpress_1  |   -> (2/6) 'acf-to-rest-api' not found. Installing... ✓
wordpress_1  |   -> (3/6) 'acf-image-crop-add-on' not found. Installing... Warning: An unexpected error occurred. Something may be wrong with WordPress.org or this server&#8217;s configuration. If you continue to have problems, please try the <a href="https://wordpress.org/support/">support forums</a>. (WordPress could not establish a secure connection to WordPress.org. Please contact your server administrator.) in /app/wp-includes/update.php on line 347
wordpress_1  | Warning: An unexpected error occurred. Something may be wrong with WordPress.org or this server&#8217;s configuration. If you continue to have problems, please try the <a href="https://wordpress.org/support/">support forums</a>. (WordPress could not establish a secure connection to WordPress.org. Please contact your server administrator.) in /app/wp-includes/update.php on line 347
wordpress_1  | Warning: An unexpected error occurred. Something may be wrong with WordPress.org or this server&#8217;s configuration. If you continue to have problems, please try the <a href="https://wordpress.org/support/">support forums</a>. (WordPress could not establish a secure connection to WordPress.org. Please contact your server administrator.) in /app/wp-includes/update.php on line 525
wordpress_1  | ✓
wordpress_1  |   -> (4/6) 'wordpress-importer' not found. Installing... Warning: An unexpected error occurred. Something may be wrong with WordPress.org or this server&#8217;s configuration. If you continue to have problems, please try the <a href="https://wordpress.org/support/">support forums</a>. (WordPress could not establish a secure connection to WordPress.org. Please contact your server administrator.) in /app/wp-includes/update.php on line 525
wordpress_1  | ✓
wordpress_1  |   -> (5/6) 'post-types-order' not found. Installing... Warning: An unexpected error occurred. Something may be wrong with WordPress.org or this server&#8217;s configuration. If you continue to have problems, please try the <a href="https://wordpress.org/support/">support forums</a>. (WordPress could not establish a secure connection to WordPress.org. Please contact your server administrator.) in /app/wp-includes/update.php on line 525
wordpress_1  | ✓
wordpress_1  |   -> (6/6) 'soil' not found. Installing... Warning: An unexpected error occurred. Something may be wrong with WordPress.org or this server&#8217;s configuration. If you continue to have problems, please try the <a href="https://wordpress.org/support/">support forums</a>. (WordPress could not establish a secure connection to WordPress.org. Please contact your server administrator.) in /app/wp-includes/update.php on line 347
wordpress_1  | Warning: An unexpected error occurred. Something may be wrong with WordPress.org or this server&#8217;s configuration. If you continue to have problems, please try the <a href="https://wordpress.org/support/">support forums</a>. (WordPress could not establish a secure connection to WordPress.org. Please contact your server administrator.) in /app/wp-includes/update.php on line 525
wordpress_1  | ✓
wordpress_1  | ==> Checking for orphaned plugins
wordpress_1  |   -> 'akismet' no longer needed. Pruning... ✓
wordpress_1  |   -> 'hello' no longer needed. Pruning... ✓
wordpress_1  | ==> Finalizing
wordpress_1  |   -> Generating .htaccess file ✓
wordpress_1  |   -> Adjusting file permissions ✓
wordpress_1  | ===============================================================================
wordpress_1  |                        WordPress Configuration Complete!
wordpress_1  | ===============================================================================
wordpress_1  | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.3. Set the 'ServerName' directive globally to suppress this message
wordpress_1  | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.3. Set the 'ServerName' directive globally to suppress this message
wordpress_1  | [Sun Dec 03 19:06:58.933511 2017] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.10 (Debian) PHP/7.0.14 configured -- resuming normal operations
wordpress_1  | [Sun Dec 03 19:06:58.933566 2017] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
wordpress_1  | 172.18.0.1 - - [03/Dec/2017:19:10:23 +0000] "GET / HTTP/1.1" 200 360 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36"
wordpress_1  | 172.18.0.1 - - [03/Dec/2017:19:10:30 +0000] "GET /wp-admin HTTP/1.1" 301 584 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36"
wordpress_1  | 172.18.0.1 - - [03/Dec/2017:19:10:30 +0000] "GET /wp-admin/ HTTP/1.1" 302 444 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36"
wordpress_1  | 172.18.0.1 - - [03/Dec/2017:19:12:32 +0000] "GET / HTTP/1.1" 200 360 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36"
wordpress_1  | 172.18.0.1 - - [03/Dec/2017:19:12:38 +0000] "GET /wp-login.php HTTP/1.1" 200 1526 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36"
wordpress_1  | 172.18.0.1 - - [03/Dec/2017:19:13:05 +0000] "GET / HTTP/1.1" 200 360 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36"
wordpress_1  | 172.18.0.1 - - [03/Dec/2017:19:13:22 +0000] "GET / HTTP/1.1" 200 360 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36"


```

**Comment by dsifford** [comment]
Two things could be happening:

1. The most obvious issue could be that the command you're running is incorrect. It should be `docker-compose up`, not `docker-compose up wordpress`. The latter only starts the wordpress service and not the database service.
2. You also will likely need to do a `URL_REPLACE` for the urls in the production site. So, if your production site url is `https://example.com`, you should set the `URL_REPLACE` environment variable to `https://example.com,http://localhost:8080`.

**Comment by dsifford** [comment]
Just noticed that you have `URL_REPLACE` set (sorry, only skimmed over your comment).

Try running the correct `up` command form and see if that helps

**Comment by lukasholzer** [comment]
@dsifford but the DB service is automatically started because it is linked

### docker-compose.yml
```yml
  wordpress:
     links:
        - db:mysql
```
