### ISSUE TITLE
docker-compose up stops always on same line

### ISSUE THREAD

**Issue by lukasholzer** [visiblevc/wordpress-starter#125]
When I run `docker-compose up` it always stops on the sime line and freezes there. 
Always at: `wordpress_1  | ==> Waiting for MySQL to initialize...`

Everything is on the master branch of [this repo](https://github.com/lukasholzer/sls-eventservice
)
## Overview

- `docker-compose up ` stops always at the same line
- Mac OSX 10.13.1
- Docker version 17.09.1-ce, build 19e2cf6

## `docker-compose.yml`

```yml
version: '3'

services:

  wordpress:
    image: visiblevc/wordpress:0.17.0-php7.2
    ports:
      - "8080:80"
    restart: always
    networks:
      - frontend
    depends_on:
      - db
    volumes:
      - ./data:/data # If mysql database dump is as .sql file inside
      - ./uploads:/app/wp-content/uploads
      - ./theme:/app/wp-content/themes/sls
      - ./config/tweaks.ini:/usr/local/etc/php/conf.d/tweaks.ini # Optional tweaks to the php.ini config
    environment:
      DB_NAME: u44750db1
      DB_HOST: db
      DB_PASS: root
      DB_PREFIX: ghth_
      SERVER_NAME: localhost
      ADMIN_EMAIL: lukas.holzer@typeflow.cc
      WP_DEBUG: 'true'
      URL_REPLACE: http://www.sls-eventservice.ch,http://localhost:8080
      PLUGINS: >-
        acf-to-rest-api,
        acf-image-crop-add-on,
        wordpress-importer,
        post-types-order,
        [soil]https://github.com/roots/soil/archive/3.7.1.zip,
        [sls-tiny-mce]https://github.com/lukasholzer/sls-tiny-mce/archive/master.zip,
        [advanced-custom-fields-pro]https://github.com/wp-premium/advanced-custom-fields-pro/archive/5.6.2.zip,

  frontend:
    networks:
      - frontend
    depends_on:
      - wordpress
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4400:4400" # HMR Server
      - "3000:3000" # BrowserSync
      - "3001:3001" # BrwoserSync Admin interface
    volumes:
      # - ./theme/src:/opt/hmrserver/src
      - ./theme:/opt/hmrserver/theme
  db:
    image: mariadb:10
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - data:/var/lib/mysql

volumes:
  data:
  uploads:
    driver: local

networks:
  frontend:

```

## Project structure

```
/data
- /web
 `- /e39931
 `- - /html
 `- - -  ...
- /u44750db1.sql
/theme
```

## `docker-compose up` output

``` bash
$ docker-compose up
Creating network "slseventservice_default" with the default driver
Creating network "slseventservice_frontend" with the default driver
Creating volume "slseventservice_data" with default driver
Creating volume "slseventservice_uploads" with local driver
Creating slseventservice_db_1 ... 
Creating slseventservice_db_1 ... done
Creating slseventservice_wordpress_1 ... 
Creating slseventservice_wordpress_1 ... done
Creating slseventservice_frontend_1 ... 
Creating slseventservice_frontend_1 ... done
Attaching to slseventservice_db_1, slseventservice_wordpress_1, slseventservice_frontend_1
db_1         | Initializing database
wordpress_1  | ===============================================================================
wordpress_1  |                          Begin WordPress Installation
wordpress_1  | ===============================================================================
wordpress_1  | ==> Downloading WordPress
wordpress_1  | Downloading WordPress 4.9.1 (en_US)...
frontend_1   | 
frontend_1   | > sls-eventservice@1.0.0 frontend /opt/hmrserver
frontend_1   | > node webpack.middleware.js
frontend_1   | 
db_1         | 
db_1         | PLEASE REMEMBER TO SET A PASSWORD FOR THE MariaDB root USER !
db_1         | To do so, start the server, then issue the following commands:
db_1         | 
db_1         | '/usr/bin/mysqladmin' -u root password 'new-password'
db_1         | '/usr/bin/mysqladmin' -u root -h  password 'new-password'
db_1         | 
db_1         | Alternatively you can run:
db_1         | '/usr/bin/mysql_secure_installation'
db_1         | 
db_1         | which will also give you the option of removing the test
db_1         | databases and anonymous user created by default.  This is
db_1         | strongly recommended for production servers.
db_1         | 
db_1         | See the MariaDB Knowledgebase at http://mariadb.com/kb or the
db_1         | MySQL manual for more instructions.
db_1         | 
db_1         | Please report any problems at http://mariadb.org/jira
db_1         | 
db_1         | The latest information about MariaDB is available at http://mariadb.org/.
db_1         | You can find additional information about the MySQL part at:
db_1         | http://dev.mysql.com
db_1         | Consider joining MariaDB's strong and vibrant community:
db_1         | https://mariadb.org/get-involved/
db_1         | 
db_1         | Database initialized
db_1         | MySQL init process in progress...
db_1         | 2017-12-20  7:15:43 139647859341184 [Note] mysqld (mysqld 10.2.11-MariaDB-10.2.11+maria~jessie) starting as process 101 ...
db_1         | 2017-12-20  7:15:43 139647859341184 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
db_1         | 2017-12-20  7:15:43 139647859341184 [Note] InnoDB: Uses event mutexes
db_1         | 2017-12-20  7:15:43 139647859341184 [Note] InnoDB: Compressed tables use zlib 1.2.8
db_1         | 2017-12-20  7:15:43 139647859341184 [Note] InnoDB: Using Linux native AIO
db_1         | 2017-12-20  7:15:43 139647859341184 [Note] InnoDB: Number of pools: 1
db_1         | 2017-12-20  7:15:43 139647859341184 [Note] InnoDB: Using SSE2 crc32 instructions
db_1         | 2017-12-20  7:15:43 139647859341184 [Note] InnoDB: Initializing buffer pool, total size = 256M, instances = 1, chunk size = 128M
db_1         | 2017-12-20  7:15:43 139647859341184 [Note] InnoDB: Completed initialization of buffer pool
db_1         | 2017-12-20  7:15:43 139647123920640 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
db_1         | 2017-12-20  7:15:43 139647859341184 [Note] InnoDB: Highest supported file format is Barracuda.
db_1         | 2017-12-20  7:15:43 139647859341184 [Note] InnoDB: 128 out of 128 rollback segments are active.
db_1         | 2017-12-20  7:15:43 139647859341184 [Note] InnoDB: Creating shared tablespace for temporary tables
db_1         | 2017-12-20  7:15:43 139647859341184 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
db_1         | 2017-12-20  7:15:43 139647859341184 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
db_1         | 2017-12-20  7:15:43 139647859341184 [Note] InnoDB: 5.7.20 started; log sequence number 1619987
db_1         | 2017-12-20  7:15:43 139646684092160 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
db_1         | 2017-12-20  7:15:43 139647859341184 [Note] Plugin 'FEEDBACK' is disabled.
db_1         | 2017-12-20  7:15:43 139646684092160 [Note] InnoDB: Buffer pool(s) load completed at 171220  7:15:43
db_1         | 2017-12-20  7:15:43 139647859341184 [Warning] 'user' entry 'root@2462213bde44' ignored in --skip-name-resolve mode.
db_1         | 2017-12-20  7:15:43 139647859341184 [Warning] 'proxies_priv' entry '@% root@2462213bde44' ignored in --skip-name-resolve mode.
db_1         | 2017-12-20  7:15:43 139647859341184 [Note] Reading of all Master_info entries succeded
db_1         | 2017-12-20  7:15:43 139647859341184 [Note] Added new Master_info '' to hash table
db_1         | 2017-12-20  7:15:43 139647859341184 [Note] mysqld: ready for connections.
db_1         | Version: '10.2.11-MariaDB-10.2.11+maria~jessie'  socket: '/var/run/mysqld/mysqld.sock'  port: 0  mariadb.org binary distribution
frontend_1   | Running on http://localhost:4400
db_1         | Warning: Unable to load '/usr/share/zoneinfo/leap-seconds.list' as time zone. Skipping it.
db_1         | 2017-12-20  7:15:45 139647709214464 [Warning] 'proxies_priv' entry '@% root@2462213bde44' ignored in --skip-name-resolve mode.
db_1         | 
db_1         | 2017-12-20  7:15:45 139647708911360 [Note] mysqld (unknown): Normal shutdown
db_1         | 
db_1         | 2017-12-20  7:15:45 139647708911360 [Note] Event Scheduler: Purging the queue. 0 events
db_1         | 2017-12-20  7:15:45 139647002851072 [Note] InnoDB: FTS optimize thread exiting.
db_1         | 2017-12-20  7:15:45 139647708911360 [Note] InnoDB: Starting shutdown...
db_1         | 2017-12-20  7:15:45 139646684092160 [Note] InnoDB: Dumping buffer pool(s) to /var/lib/mysql/ib_buffer_pool
db_1         | 2017-12-20  7:15:45 139646684092160 [Note] InnoDB: Buffer pool(s) dump completed at 171220  7:15:45
frontend_1   | 
frontend_1   | [at-loader] Using typescript@2.5.0 from typescript and "tsconfig.json" from /opt/hmrserver/theme/src/tsconfig.json.
frontend_1   | 
db_1         | 2017-12-20  7:15:47 139647708911360 [Note] InnoDB: Shutdown completed; log sequence number 1620015
db_1         | 2017-12-20  7:15:47 139647708911360 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
db_1         | 2017-12-20  7:15:47 139647708911360 [Note] mysqld: Shutdown complete
db_1         | 
db_1         | 
db_1         | MySQL init process done. Ready for start up.
db_1         | 
db_1         | 2017-12-20  7:15:47 140396502574976 [Note] mysqld (mysqld 10.2.11-MariaDB-10.2.11+maria~jessie) starting as process 1 ...
db_1         | 2017-12-20  7:15:47 140396502574976 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
db_1         | 2017-12-20  7:15:47 140396502574976 [Note] InnoDB: Uses event mutexes
db_1         | 2017-12-20  7:15:47 140396502574976 [Note] InnoDB: Compressed tables use zlib 1.2.8
db_1         | 2017-12-20  7:15:47 140396502574976 [Note] InnoDB: Using Linux native AIO
db_1         | 2017-12-20  7:15:47 140396502574976 [Note] InnoDB: Number of pools: 1
db_1         | 2017-12-20  7:15:47 140396502574976 [Note] InnoDB: Using SSE2 crc32 instructions
db_1         | 2017-12-20  7:15:47 140396502574976 [Note] InnoDB: Initializing buffer pool, total size = 256M, instances = 1, chunk size = 128M
db_1         | 2017-12-20  7:15:47 140396502574976 [Note] InnoDB: Completed initialization of buffer pool
db_1         | 2017-12-20  7:15:47 140395766568704 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
db_1         | 2017-12-20  7:15:47 140396502574976 [Note] InnoDB: Highest supported file format is Barracuda.
db_1         | 2017-12-20  7:15:47 140396502574976 [Note] InnoDB: 128 out of 128 rollback segments are active.
db_1         | 2017-12-20  7:15:47 140396502574976 [Note] InnoDB: Creating shared tablespace for temporary tables
db_1         | 2017-12-20  7:15:47 140396502574976 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
db_1         | 2017-12-20  7:15:47 140396502574976 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
db_1         | 2017-12-20  7:15:47 140396502574976 [Note] InnoDB: 5.7.20 started; log sequence number 1620015
db_1         | 2017-12-20  7:15:47 140395602228992 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
db_1         | 2017-12-20  7:15:47 140395602228992 [Note] InnoDB: Buffer pool(s) load completed at 171220  7:15:47
db_1         | 2017-12-20  7:15:47 140396502574976 [Note] Plugin 'FEEDBACK' is disabled.
db_1         | 2017-12-20  7:15:47 140396502574976 [Note] Server socket created on IP: '::'.
db_1         | 2017-12-20  7:15:47 140396502574976 [Warning] 'proxies_priv' entry '@% root@2462213bde44' ignored in --skip-name-resolve mode.
db_1         | 2017-12-20  7:15:47 140396502574976 [Note] Reading of all Master_info entries succeded
db_1         | 2017-12-20  7:15:47 140396502574976 [Note] Added new Master_info '' to hash table
db_1         | 2017-12-20  7:15:47 140396502574976 [Note] mysqld: ready for connections.
db_1         | Version: '10.2.11-MariaDB-10.2.11+maria~jessie'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
frontend_1   | 
frontend_1   | [at-loader] Checking started in a separate process...
frontend_1   | 
frontend_1   | [at-loader] Ok, 0.424 sec.
frontend_1   | webpack built 50ae8d19e68cdafb01a5 in 6297ms
wordpress_1  | md5 hash verified: 111ecbfc98633103e1fc1105c0c00c76
wordpress_1  | Success: WordPress downloaded.
wordpress_1  | Success: Wordpress downloaded
wordpress_1  | ==> Waiting for MySQL to initialize...
```
