### ISSUE TITLE
PhpMyadmin access

### ISSUE THREAD

**Issue by dblodorn** [visiblevc/wordpress-starter#127]
Hi - simple question,
I can't seem to access the phpmyadmin service:

localhost:8080/phpmyadmin

- just returns a 404 in wordpress.

Perhaps a hint towards how to use phpmyadmin in this setup would be great in the documentation. 
-- And thanks for this whole setup, its really changed my wp development for the better!

**Comment by dsifford** [comment]
Glad it's working well for you @dblodorn 

Assuming you used [our example](https://github.com/visiblevc/wordpress-starter/tree/master/example) as a starting point, your `docker-compose.yml` file should look something like this....

```yml
version: '3'
services:
  wordpress:
    # same as above
  db:
    # same as above
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 22222:80
volumes:
  data:
```

If the above assumptions are correct, then the issue you're having is simply the fact that you're trying to access the `phpmyadmin` service from the wrong location.

Instead of `localhost:8080/phpmyadmin`, the `phpmyadmin` service of the above configuration would be located at `localhost:22222` (note the port mapping).

Hope that helps.
