### ISSUE TITLE
Wrong URL from plugin

### ISSUE THREAD

**Issue by zagreusinoz** [visiblevc/wordpress-starter#129]
## Overview

I'm mounting plugins that I'm developing as the documentation says and in my plugin I'm trying to get the url of some scripts like this:
```$path = dirname(plugin_dir_url( __FILE__ )) . '/scripts/';```

However this returns the URL:
```http://localhost:8080/app/wp-content/plugins/customer-manager/scripts/js/script.js?ver=5.6.8```

whereas the actual URL should be:
```http://localhost:8080/wp-content/plugins/customer-manager/scripts/js/script.js?ver=5.6.8```

without the app directory.

Any help would be much appreciated. Thanks!

## `docker-compose.yml`

```yml
version: '3'
services:
  wordpress:
    image: visiblevc/wordpress:0.17.0-php7.1
    ports:
      - 8080:80
      - 443:443
    volumes:
      - ./data:/data
      - ./themes/marsjam-customer-theme:/app/wp-content/themes/customer-theme
      - ./plugins/marsjam-customer:/app/wp-content/plugins/customer
      - ./plugins/marsjam-customer-manager:/app/wp-content/plugins/customer-manager
      - ./../config/php.ini:/usr/local/etc/php/conf.d/php.ini
    environment:
      WP_VERSION: latest
      DB_NAME: wordpress
      DB_PASS: root
      WP_DEBUG: 'true'
      WP_DEBUG_DISPLAY: 'true'
      WP_DEBUG_LOG: 'true'
      PLUGINS: >-
        bulk-delete
      THEMES: >-
        bootstrap-basic4

  db:
    image: mariadb:10 # or mysql:5.7
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 22222:80

volumes:
  data:

```
