### ISSUE TITLE
mysql:5.7 hangs on waiting for MySQL to initialize

### ISSUE THREAD

**Issue by martintburgess** [visiblevc/wordpress-starter#151]
## Overview
Thanks for a great repo. 
I am trying to run /example/docker-compose.yml using mysql:5.7 instead of mariadb:10
This is the only change to the docker-compose.yml.
Installation doesn't get passed "Waiting for MySQL to initialize...".

Issue does not occur with mariadb:10

mac os x 10.14.2
docker version 18.09.0

## `docker-compose.yml`

```yml
version: "3"
services:
    wordpress:
        image: visiblevc/wordpress

        # required for mounting bindfs
        cap_add:
            - SYS_ADMIN
        devices:
            - /dev/fuse
        # required on certain cloud hosts
        security_opt:
            - apparmor:unconfined

        ports:
            - 8080:80
            - 443:443
        volumes:
            - ./data:/data
            - ./scripts:/docker-entrypoint-initwp.d
        environment:
            DB_NAME: wordpress
            DB_PASS: root
            PLUGINS: >-
                academic-bloggers-toolkit
                co-authors-plus
                [WP-API]https://github.com/WP-API/WP-API/archive/master.zip

    db:
        image: mysql:5.7 # mariadb:10 
        volumes:
            - data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 22222:80

volumes:
    data:
```

## Project structure
same as /example

## `docker-compose up` output

```
wordpress_1   | ======================================================================
wordpress_1   |                     Begin WordPress Installation                    
wordpress_1   | ======================================================================
wordpress_1   | ==> Downloading WordPress
wordpress_1   |          Downloading WordPress 5.0.1 (en_US)...
wordpress_1   |          md5 hash verified: ae286aad683f26c19ce3e4cff91b5661
wordpress_1   | Success: WordPress downloaded.
wordpress_1   | ==> Waiting for MySQL to initialize...
```

**Comment by dsifford** [comment]
@martintburgess Can you explain further what the issue is you're having. The output I'm seeing looks correct.

**Comment by martintburgess** [comment]
@dsifford the installation doesn't get past this point. Waited considerable time (15 minutes or more) and was stuck there.

**Comment by dsifford** [comment]
Ah... ok got it. Not sure why, but I will confess that I generally always use MariaDB... I'll check into this tomorrow.

**Comment by dsifford** [comment]
No worries. I appreciate you reaching out. They _should_ in theory both be backwards compatible with each other so it's a bit strange that this would occur.

**Comment by dsifford** [comment]
Finally got around to trying this and I can't reproduce. Is this still giving you trouble @martintburgess?

**Comment by martintburgess** [comment]
@dsifford Just tried removing all my containers and images as well as recloning the wordpress-starter repo - still doesn't get past `==> Waiting for MySQL to initialize...`. I'm happy to use a mariadb, so it's no trouble for me.

**Comment by dsifford** [comment]
Hm... very odd. Perhaps it has something to do with the machine you're on?

I'll leave this issue open for now until we can get another person who runs into this to chime in.

**Comment by jiverson** [comment]
Probably just need to change the port to mysql in the db section.

```yml
...
db:
    image: mariadb:10 # or mysql:5.7
    ports:
        - 3307:3306 # change ip if required
...
```
