### ISSUE TITLE
Contradicting docker-compose.yml examples.

### ISSUE THREAD

**Issue by BobbyBabes** [visiblevc/wordpress-starter#152]
## Overview

- What's your problem about?
Contradicting ```docker-compose.yml``` displayed on Quickstart page, and in ```example``` folder download. Which one is the current example?
- What is your operating system?
N/A
- What is your docker version? `docker version`
N/A

## `docker-compose.yml`
In the folder named ```example``` downloaded from the [Quickstart page](https://github.com/visiblevc/wordpress-starter/tree/master/example#quickstart) and identical (of course) to the one in the repo. Download link shown right below the line _"Download this example to your current working directory"_.

```yml
version: "3"
services:
    wordpress:
        image: visiblevc/wordpress

        # required for mounting bindfs
        cap_add:
            - SYS_ADMIN
        devices:
            - /dev/fuse
        # required on certain cloud hosts
        security_opt:
            - apparmor:unconfined

        ports:
            - 8080:80
            - 443:443
        volumes:
            - ./data:/data
            - ./scripts:/docker-entrypoint-initwp.d
        environment:
            DB_NAME: wordpress
            DB_PASS: root
            PLUGINS: >-
                academic-bloggers-toolkit
                co-authors-plus
                [WP-API]https://github.com/WP-API/WP-API/archive/master.zip

    db:
        image: mariadb:10 # or mysql:5.7
        volumes:
            - data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 22222:80

volumes:
    data:
```

## `docker-compose.yml`
Shown on the same [Quickstart page](https://github.com/visiblevc/wordpress-starter/tree/master/example#quickstart) below the line _"The only thing you need to get started is a docker-compose.yml file:"_.

```yml
version: '3'
services:
  wordpress:
    image: visiblevc/wordpress:latest
    ports:
      - 8080:80
      - 443:443
    volumes:
      - ./data:/data # Required if importing an existing database
      - ./tweaks.ini:/usr/local/etc/php/conf.d/tweaks.ini # Optional tweaks to the php.ini config
      - ./wp-content/uploads:/app/wp-content/uploads
      - ./yourplugin:/app/wp-content/plugins/yourplugin # Plugin development
      - ./yourtheme:/app/wp-content/themes/yourtheme   # Theme development
    environment:
      DB_HOST: db # must match db service name below
      DB_NAME: wordpress
      DB_PASS: root # must match below
      PLUGINS: >-
        academic-bloggers-toolkit,
        co-authors-plus,
        [WP-API]https://github.com/WP-API/WP-API/archive/master.zip,
      URL_REPLACE: localhost:8080
      WP_DEBUG: 'true'
  db:
    image: mysql:5.7 # or mariadb:10
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
volumes:
  data: {}
```

## Project structure

```
N/A
```

## `docker-compose up` output

```
N/A
```
