### ISSUE TITLE
Theme from volumes deleted

### ISSUE THREAD

**Issue by keskistok** [visiblevc/wordpress-starter#158]
```        volumes:
            - ./data:/data
            - ./code/stokpress:/app/wp-content/themes/stokpress```

**Comment by dsifford** [comment]
Hard to tell without the full `docker-compose.yml`. Can you try maybe not having your theme named with a slash?

**Comment by keskistok** [comment]
Here is the full composer:

```
version: "3"
services:
    wordpress:
        image: visiblevc/wordpress

        # required for mounting bindfs
        cap_add:
            - SYS_ADMIN
        devices:
            - /dev/fuse
        # required on certain cloud hosts
        security_opt:
            - apparmor:unconfined

        ports:
            - 9080:80
        volumes:
            - ./data:/data
            - ./code/stokpress:/app/wp-content/themes/stokpress
            - ./scripts:/docker-entrypoint-initwp.d
        environment:
            DB_NAME: wordpress
            DB_PASS: root
            PLUGINS: >-
                classic-editor
                safe-svg
                [soil]https://github.com/roots/soil/archive/3.7.3.zip

    db:
        image: mariadb:10 # or mysql:5.7
        volumes:
            - data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports: 
            - 5306:3306

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 32222:80

volumes:
    data:

```
Im not really sure why the theme name ends up like that, but I guess its because of the specific file structure used by the sage theme.

https://github.com/roots/sage/blob/master/resources/style.css
