### ISSUE TITLE
Installing XDebug and Mailhog

### ISSUE THREAD

**Issue by yanickvanbarneveld** [visiblevc/wordpress-starter#163]
### What's your problem about?
I am trying to enable XDebug and Mailhog in the visiblevc/wordpress image by extending the Dockerfile. I don't get it to work, when I build I get the following error:

```
Cannot install, php_dir for channel "pecl.php.net" is not writeable by the current user
ERROR: Service 'wordpress' failed to build: The command '/bin/bash -o pipefail -c yes | pecl install xdebug     && echo "zend_extension=$(find /usr/local/lib/php/extensions/ -name xdebug.so)" > /usr/local/etc/php/conf.d/xdebug.ini     && echo "xdebug.remote_enable=1" >> /usr/local/etc/php/conf.d/xdebug.ini     && echo "xdebug.remote_autostart=1" >> /usr/local/etc/php/conf.d/xdebug.ini     && echo "xdebug.profiler_enable=1" >> /usr/local/etc/php/conf.d/xdebug.ini     && echo "xdebug.profiler_output_name=cachegrind.out.%t" >> /usr/local/etc/php/conf.d/xdebug.ini     && echo "xdebug.profiler_output_dir=/tmp" >> /usr/local/etc/php/conf.d/xdebug.ini     && echo "max_input_vars=2000" >> /usr/local/etc/php/conf.d/custom.ini     && rm -rf /usr/local/etc/php/conf.d/opcache-recommended.ini' returned a non-zero code: 1
```

Did someone else manage to achieve this?

## `docker-compose.yml & Dockerfile`

```Dockerfile
FROM visiblevc/wordpress:latest

# # Mailhog
RUN curl --location --output /usr/local/bin/mhsendmail https://github.com/mailhog/mhsendmail/releases/download/v0.2.0/mhsendmail_linux_amd64 && \
	chmod +x /usr/local/bin/mhsendmail

RUN echo 'sendmail_path="/usr/local/bin/mhsendmail --smtp-addr=mailhog:1025 --from=noreply@info.nl"' > /usr/local/etc/php/conf.d/mailhog.ini

# Xdebug
ENV XDEBUG_PORT 9000

RUN yes | pecl install xdebug \
    && echo "zend_extension=$(find /usr/local/lib/php/extensions/ -name xdebug.so)" > /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.remote_enable=1" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.remote_autostart=1" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.profiler_enable=1" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.profiler_output_name=cachegrind.out.%t" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.profiler_output_dir=/tmp" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "max_input_vars=2000" >> /usr/local/etc/php/conf.d/custom.ini \
    && rm -rf /usr/local/etc/php/conf.d/opcache-recommended.ini

EXPOSE 9000
```

```yml
version: "3.7"
services:
  wordpress:
    build:
      context: ./
      dockerfile: ./Dockerfile
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfined
    ports:
      - 8080:80
      - 443:443
    environment:
      DB_NAME: wordpress
      DB_PASS: root
    volumes:
      - ./data/database:/data:cached
      - ./data/wordpress:/app:cached
      - ./build/themes:/app/wp-content/themes:cached
      - ./build/uploads:/app/wp-content/uploads:cached
      - ./build/plugins:/app/wp-content/plugins:cached
  db:
    image: mariadb:10
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8000:80
  mailhog:
    image: mailhog/mailhog
    depends_on:
      - wordpress
    ports:
      - "1025:1025"
      - "8025:8025"
volumes:
  data: null
```
