### ISSUE TITLE
Can't install Plugins

### ISSUE THREAD

**Issue by jaronoff** [visiblevc/wordpress-starter#36]
I'm getting an error when I try to install plugins. In the theme that I bought, are zip files of 3 plugins. They are showing up in the plugins area after installing the theme, but I get an error when I try to install them.

Error:
The plugin does not have a valid header.
Downloading install package from http://localhost:8080/wp-content/themes/wprentals/libs/plugins/revslider.zip…
Download failed. cURL error 7: Failed to connect to localhost port 8080: Connection refused

<img width="930" alt="install_required_plugins_ _dr_eco_adventures_ _wordpress" src="https://cloud.githubusercontent.com/assets/433966/17714431/c069b778-63cd-11e6-87b6-2e234f33d3ab.png">

Here's my docker-compose.yml file: http://pastebin.com/YhnDvm2S

**Comment by jaronoff** [comment]
ALSO, is there a place to set the memory limit, or bump that up in the docker-compose.yml?

**Comment by dsifford** [comment]
@jaronoff 

Do you have the plugins directory volumed? If you volume the _entire_ directory, rather than just the individual subdirectories, you won't be able to install or remove plugins using the wordpress installer due to permissions issues.

**Comment by dsifford** [comment]
Also, your volumes are not correct:

```yml
volumes:
      - ./data:/data
      - ./data/wp-rentals:/app/wp-content/themes/
      - ./data/wp-rentals/wprentals/libs/plugins:/app/wp-content/plugins
```
You should not have the plugins and themes directory inside the data directory. This creates a circular reference and will cause errors.

**Comment by dsifford** [comment]
Can you send a screenshot of the directory structure you have locally? If so, I'll adjust the compose file for you.

**Comment by jaronoff** [comment]
Sure.

<img width="1127" alt="plugins_and_downloads" src="https://cloud.githubusercontent.com/assets/433966/17714731/fe4e31a8-63ce-11e6-9416-1824db0ca1d2.png">

**Comment by dsifford** [comment]
@jaronoff Where is the `docker-compose.yml` file in relation to the files above?

**Comment by dsifford** [comment]
Here's an idea of how you should lay out your directory and compose file...

```yml
version: '2'
services:
  wordpress:
    image: visiblevc/wordpress:latest
    links:
      - db
    ports:
      - 8080:80
      - 443:443
    volumes:
      - ./data:/data
      - ./wp-rentals:/app/wp-content/themes/wp-rentals
    environment:
      DB_NAME: wordpress
      DB_PASS: root
      PLUGINS: akismet
  db:
    image: mysql:5.7 # or mariadb
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
volumes:
  data: {}
```

```
data\
    database.sql
wp-rentals\
docker-compose.yml
```
   
Hope that helps.
