### ISSUE TITLE
Setup accommodations for HTTPS

### ISSUE THREAD

**Issue by 808loud** [visiblevc/wordpress-starter#50]
## Overview

I am trying to get an existing WordPress site's theme and database running in Docker, for local development. 

The existing (live) site is served via HTTPS. The site's WordPress Address (URL) is set to https://www.homesforheroes.com - so the protocol is stored in the WP database. 

I can get WordPress working fine, if I don't import the database. However, I need the database imported for development purposes.

So I am importing the production site's database, following your examples, and that seems to be working (tables are visible on the mysql container), however...

When I try to load to the site on my host machine (at http://localhost:8080), I get redirected to `https://localhost:8080/` but WordPress doesn't load. Instead, I get the following message in Chrome:

```
This site can’t provide a secure connection
localhost sent an invalid response.
Try running Network Diagnostics.
ERR_SSL_PROTOCOL_ERROR
```

Host OS: macOS Sierra
`Docker version 1.12.1, build 6f9534c`
`docker-compose version 1.8.0, build f3628c7`

I have tried adjusting the ports of the wordpress container, as well as adjusting the `SEARCH_REPLACE` strings, to no avail. Although, I am a relative noob when it comes to Docker, sysadmin, and port forwarding, so it is most definitely possible that the changes I attempted were incorrect.

Is there something obvious that I'm missing, either in the port setup, the `SEARCH_REPLACE', or elsewhere? Any tips? Thanks in advance.
## `docker-compose.yml`

``` yml
version: '2'
services:
  wordpress:
    image: visiblevc/wordpress:latest
    links:
      - db
    ports:
      - 8080:80
      - 443:443
    volumes:
      - ./data:/data
      - ./wp-content/themes/enfold:/app/wp-content/themes/enfold
      - ./wp-content/uploads:/app/wp-content/uploads
    environment:
      DB_NAME: wordpress
      DB_PASS: root # must match db:environment:MYSQL_ROOT_PASSWORD below
      DB_PREFIX: hfh_
      PLUGINS: >-
        advanced-custom-fields,
        css-hero,
        css-plus,
        header-footer,
        redirection,
        timeline-express,
        wordpress-seo,
      SEARCH_REPLACE: https://www.homesforheroes.com,http://localhost:8080
      WP_DEBUG: 'true'
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
volumes:
  data: {}
```
## Project structure

```
/data
  /database.sql
/wp-content
  /themes
    /enfold
.editorconfig
.gitignore
docker-compose.yml
Dockerfile
gulpfile.js
package.json
run.sh
```
## `docker-compose up` output

```
Creating homesforheroescom_db_1
Creating homesforheroescom_wordpress_1
Attaching to homesforheroescom_db_1, homesforheroescom_wordpress_1
db_1         | 2016-10-27T19:48:19.077424Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
db_1         | 2016-10-27T19:48:19.081194Z 0 [Note] mysqld (mysqld 5.7.16) starting as process 1 ...
db_1         | 2016-10-27T19:48:19.089431Z 0 [Note] InnoDB: PUNCH HOLE support available
db_1         | 2016-10-27T19:48:19.089491Z 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
db_1         | 2016-10-27T19:48:19.089504Z 0 [Note] InnoDB: Uses event mutexes
db_1         | 2016-10-27T19:48:19.089517Z 0 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
db_1         | 2016-10-27T19:48:19.089545Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.3
db_1         | 2016-10-27T19:48:19.089556Z 0 [Note] InnoDB: Using Linux native AIO
db_1         | 2016-10-27T19:48:19.089995Z 0 [Note] InnoDB: Number of pools: 1
db_1         | 2016-10-27T19:48:19.090156Z 0 [Note] InnoDB: Using CPU crc32 instructions
db_1         | 2016-10-27T19:48:19.094560Z 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
db_1         | 2016-10-27T19:48:19.109649Z 0 [Note] InnoDB: Completed initialization of buffer pool
db_1         | 2016-10-27T19:48:19.113006Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
db_1         | 2016-10-27T19:48:19.132581Z 0 [Note] InnoDB: Highest supported file format is Barracuda.
db_1         | 2016-10-27T19:48:19.252556Z 0 [Note] InnoDB: Creating shared tablespace for temporary tables
db_1         | 2016-10-27T19:48:19.253563Z 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
db_1         | 2016-10-27T19:48:19.677205Z 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
db_1         | 2016-10-27T19:48:19.679760Z 0 [Note] InnoDB: 96 redo rollback segment(s) found. 96 redo rollback segment(s) are active.
db_1         | 2016-10-27T19:48:19.679921Z 0 [Note] InnoDB: 32 non-redo rollback segment(s) are active.
db_1         | 2016-10-27T19:48:19.681078Z 0 [Note] InnoDB: 5.7.16 started; log sequence number 26805051
db_1         | 2016-10-27T19:48:19.681737Z 0 [Note] Plugin 'FEDERATED' is disabled.
db_1         | 2016-10-27T19:48:19.684611Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
db_1         | 2016-10-27T19:48:19.692721Z 0 [Warning] Failed to set up SSL because of the following SSL library error: SSL context is not usable without certificate and private key
db_1         | 2016-10-27T19:48:19.694904Z 0 [Note] Server hostname (bind-address): '*'; port: 3306
db_1         | 2016-10-27T19:48:19.695352Z 0 [Note] IPv6 is available.
wordpress_1  | ===============================================================================
wordpress_1  |                          Begin WordPress Installation
wordpress_1  | ===============================================================================
db_1         | 2016-10-27T19:48:19.695494Z 0 [Note]   - '::' resolves to '::';
db_1         | 2016-10-27T19:48:19.695833Z 0 [Note] Server socket created on IP: '::'.
db_1         | 2016-10-27T19:48:19.696357Z 0 [Note] InnoDB: Buffer pool(s) load completed at 161027 19:48:19
db_1         | 2016-10-27T19:48:19.884580Z 0 [Warning] 'db' entry 'sys mysql.sys@localhost' ignored in --skip-name-resolve mode.
db_1         | 2016-10-27T19:48:19.884877Z 0 [Warning] 'proxies_priv' entry '@ root@localhost' ignored in --skip-name-resolve mode.
db_1         | 2016-10-27T19:48:19.908121Z 0 [Warning] 'tables_priv' entry 'sys_config mysql.sys@localhost' ignored in --skip-name-resolve mode.
db_1         | 2016-10-27T19:48:19.918407Z 0 [Note] Event Scheduler: Loaded 0 events
db_1         | 2016-10-27T19:48:19.919039Z 0 [Note] mysqld: ready for connections.
db_1         | Version: '5.7.16'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
wordpress_1  | ==> Installing WordPress
wordpress_1  |   -> Downloading... ✓
wordpress_1  | ==> Waiting for MySQL to initialize...
wordpress_1  |   ->  mysqld is alive
wordpress_1  | ==> Configuring WordPress
wordpress_1  |   -> Generating wp-config.php file... ✓
wordpress_1  | ==> Checking database
wordpress_1  |   -> Database exists. SKIPPING...
wordpress_1  | ==> Checking for multisite
wordpress_1  |   -> Multisite not found. SKIPPING...
wordpress_1  | ==> Checking themes
wordpress_1  |   -> No theme dependencies listed
wordpress_1  | ==> Checking for orphaned themes
wordpress_1  |   -> 'twentyfifteen' no longer needed. Pruning ✓
wordpress_1  |   -> 'twentyfourteen' no longer needed. Pruning ✓
wordpress_1  | ==> Checking plugins
wordpress_1  |   -> (1/7) 'advanced-custom-fields' not found. Installing... ✓
wordpress_1  |   -> (2/7) 'css-hero' not found. Installing... ✓
wordpress_1  |   -> (3/7) 'css-plus' not found. Installing... ✓
wordpress_1  |   -> (4/7) 'header-footer' not found. Installing... ✓
wordpress_1  |   -> (5/7) 'redirection' not found. Installing... ✓
wordpress_1  |   -> (6/7) 'timeline-express' not found. Installing... ✓
wordpress_1  |   -> (7/7) 'wordpress-seo' not found. Installing... ✓
wordpress_1  | ==> Checking for orphaned plugins
wordpress_1  |   -> 'akismet' no longer needed. Pruning... ✓
wordpress_1  |   -> 'hello' no longer needed. Pruning... ✓
wordpress_1  | ==> Finalizing
wordpress_1  |   -> Generating .htaccess file ✓
wordpress_1  |   -> Adjusting file permissions ✓
wordpress_1  | ===============================================================================
wordpress_1  |                        WordPress Configuration Complete!
wordpress_1  | ===============================================================================

```
