### ISSUE TITLE
plugins / themes tagged with [local] raise yaml error when first entry

### ISSUE THREAD

**Issue by b0rt** [visiblevc/wordpress-starter#56]
## not working `docker-compose.yml`

```version: '2'
services:
  wordpress:
    image: visiblevc/wordpress:latest
    links:
      - db
    ports:
      - 8080:80
      - 443:443
    volumes:
      - ./data:/data
      - ./wp-content/themes/mytheme:/app/wp-content/themes/mytheme
      - ./wp-content/plugins/myplugin:/app/wp-content/plugins/myplugin
    environment:
      DB_NAME: wordpress
      DB_PASS: root
      THEMES: [local]mytheme
      PLUGINS: [local]myplugin
  db:
    image: mysql:5.7 # or mariadb:10
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
volumes:
  data: {}
```
### error on bash
```
$ docker-compose up 
ERROR: yaml.parser.ParserError: while parsing a block mapping
  in "./docker-compose.yml", line 15, column 7
expected <block end>, but found '<scalar>'
  in "./docker-compose.yml", line 17, column 22

```

## working `docker-compose.yml`
```version: '2'
services:
  wordpress:
    image: visiblevc/wordpress:latest
    links:
      - db
    ports:
      - 8080:80
      - 443:443
    volumes:
      - ./data:/data
      - ./wp-content/themes/mytheme:/app/wp-content/themes/mytheme
      - ./wp-content/plugins/myplugin:/app/wp-content/plugins/myplugin
    environment:
      DB_NAME: wordpress
      DB_PASS: root
      THEMES: twentysixteen, [local]mytheme
      PLUGINS: piklist, [local]myplugin
  db:
    image: mysql:5.7 # or mariadb:10
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
volumes:
  data: {}
```

## Overview

- What's your problem about?
annoying yaml error
- What is your operating system?
debian stretch
- What is your docker version? `docker version`
```
docker version
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 21:45:16 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 21:45:16 2016
 OS/Arch:      linux/amd64

```

**Comment by b0rt** [comment]
found the solution: putting >- in front solves the issue :)

```
version: '2'
services:
  wordpress:
    image: visiblevc/wordpress:latest
    links:
      - db
    ports:
      - 8080:80
      - 443:443
    volumes:
      - ./data:/data
      - ./wp-content/themes/mytheme:/app/wp-content/themes/mytheme
      - ./wp-content/plugins/myplugin:/app/wp-content/plugins/myplugin
    environment:
      DB_NAME: wordpress
      DB_PASS: root
      THEMES: >-
        [local]mytheme
      PLUGINS: >-
        [local]myplugin
```
