### ISSUE TITLE
Can't start the MySQL container on Fedora 

### ISSUE THREAD

**Issue by leiluspocus** [visiblevc/wordpress-starter#83]
## Overview

- What's your problem about?
The environment is working flawlessly on Mac, thank you ! I'm trying to make it work on a coworker's laptop running on Fedora and it seems like there is not enough space on his laptop. It breaks during the docker-compose up when the script tries to run the MySQL container. 
I checked the partitions and it seems like one of them is full : https://s29.postimg.org/61y5vzn87/Screenshot_from_2017_02_01_11_38_43.png 

I tried to unmount them using Gparted but it seems like they are always busy (since I'm using a terminal for example). Hence the following question : 

Is there a way to make Docker use the /dev/sda6 partition (since there's plenty of space in it ?) 

Thank you for your support !

- What is your operating system?
Fedora 22 
- What is your docker version? `docker version`
 ~  $  docker version
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        
 OS/Arch:      linux/amd64

## `docker-compose.yml`

```yml
version: '2'
services:
  wordpress:
    image: visiblevc/wordpress:latest
    ports:
      - 8080:80
      - 443:443
    volumes:
      - ./data:/data
      - ./mytheme:/app/wp-content/themes/mytheme   # Child theme development
      - ./myplugin:/app/wp-content/plugins/myplugin # Plugin slideshows 
      - ./img:/app/wp-content/uploads/2015/04 # Base image 
    environment:
      DB_NAME: myblog
      DB_PASS: root      
      DB_PREFIX: ppt_
      PLUGINS: >-
        [local]myplugin
      THEMES: >-
        [local]mytheme
      VERBOSE: 'true'
  db:
    image: mysql:5.7 # or mysql:5.7
    volumes:
      - data:/var/lib/mysql
      - ./data:/data
    environment:
      MYSQL_ROOT_PASSWORD: root
volumes:
  data: {}
```

## Project structure

```
mytheme
CHANGELOG.md
data
docker-compose.yml
gulpfile.js
img
ISSUE_TEMPLATE.md
myplugin
package.json
php5.6
php7.0
README.md
run.sh 
```

## `docker-compose up` output

```
~  #  docker-compose up
Creating network "mydocker_default" with the default driver
Creating volume "mydocker_data" with default driver
Pulling db (mysql:5.7)...
5.7: Pulling from library/mysql
5040bd298390: Pull complete
55370df68315: Pull complete
fad5195d69cc: Pull complete
a1034a5fbbfc: Pull complete
17f3570b42ae: Pull complete
6bf4b16e5339: Pull complete
9700c9731729: Pull complete
f2fea9c5b632: Pull complete
2f8101f5336d: Pull complete
0dc8f8a1031a: Pull complete
a1b9627588c7: Pull complete
Digest: sha256:5e2ec5964847dd78c83410f228325a462a3bfd796b6133b2bdd590b71721fea6
Status: Downloaded newer image for mysql:5.7
Pulling wordpress (visiblevc/wordpress:latest)...
latest: Pulling from visiblevc/wordpress
5973cba6eb58: Pull complete
4b0b8a6e052a: Pull complete
2e71405ba09c: Pull complete
0ea2ef7620c9: Pull complete
d423fcb2500c: Pull complete
3be7de616d2c: Pull complete
4ff10eba635c: Pull complete
5d186f0ca155: Pull complete
c31e25283764: Pull complete
d2bc4176799d: Pull complete
c958da07c22e: Pull complete
b0ed76332d75: Pull complete
f674b02795e7: Pull complete
a23836d5f403: Pull complete
bf1e38b2220c: Pull complete
be7eea9d7742: Pull complete
3715583547b3: Pull complete
Digest: sha256:76d46da65bb03da7e9336ccc258e66a259a7494e16d807d7d392f5f7f5d85a25
Status: Downloaded newer image for visiblevc/wordpress:latest
Creating mydocker_db_1
Creating mydocker_wordpress_1
Attaching to mydocker_db_1, mydocker_wordpress_1
db_1         | Initializing database
db_1         | 2017-02-01T10:33:00.170264Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
db_1         | 2017-02-01T10:33:00.191032Z 0 [Warning] InnoDB: Retry attempts for writing partial data failed.
db_1         | 2017-02-01T10:33:00.191051Z 0 [ERROR] InnoDB: Write to file ./ibdata1failed at offset 0, 1048576 bytes should have been written, only 0 were written. Operating system error number 28. Check that your OS and file system support files of this size. Check also that the disk is not full or a disk quota exceeded.
db_1         | 2017-02-01T10:33:00.191059Z 0 [ERROR] InnoDB: Error number 28 means 'No space left on device'
db_1         | 2017-02-01T10:33:00.191063Z 0 [ERROR] InnoDB: Could not set the file size of './ibdata1'. Probably out of disk space
db_1         | 2017-02-01T10:33:00.191066Z 0 [ERROR] InnoDB: InnoDB Database creation was aborted with error Generic error. You may need to delete the ibdata1 file before trying to start up again.
wordpress_1  | ===============================================================================
wordpress_1  |                          Begin WordPress Installation
wordpress_1  | ===============================================================================
wordpress_1  | ==> Installing WordPress
db_1         | 2017-02-01T10:33:00.791593Z 0 [ERROR] Plugin 'InnoDB' init function returned error.
db_1         | 2017-02-01T10:33:00.791606Z 0 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
db_1         | 2017-02-01T10:33:00.791609Z 0 [ERROR] Failed to initialize plugins.
db_1         | 2017-02-01T10:33:00.791611Z 0 [ERROR] Aborting
db_1         | 
wordpress_1  |   -> Downloading... Downloading WordPress 4.7.2 (en_US)...
mydocker_db_1 exited with code 1
wordpress_1  | md5 hash verified: 17f9fe2fa6d14eba86aad152059b5afd
wordpress_1  | Success: WordPress downloaded.
wordpress_1  | ✓
wordpress_1  | ==> Waiting for MySQL to initialize...
```
It's just gonna stop here. Since MySQL can't start, the Wordpress container cannot attach to MySQL.
