### ISSUE TITLE
My themes and plugins get pruned.

### ISSUE THREAD

**Issue by musicaljoeker** [visiblevc/wordpress-starter#84]
## Overview

- What's your problem about? For whatever reason almost all my plugins and themes get deleted every time I instantiate this docker configuration. Docker says they get pruned. Is there a way to disable pruning? Even if I paste the plugins after I have Docker booted and activate them, they still get pruned on next boot.
- What is your operating system? macOS Sierra 10.12.2
- What is your docker version? 1.13.1

## `docker-compose.yml`

```
version: '2'
services:
  wordpress:
    image: visiblevc/wordpress:latest
    ports:
      - 8080:80
    volumes:
      - ./data:/data
      - ./wp-content/themes:/app/wp-content/themes
      - ./wp-content/plugins:/app/wp-content/plugins
      - ./wp-content/uploads:/app/wp-content/uploads
    environment:
      DB_NAME: wordpress
      DB_PASS: root
  db:
    image: mariadb:10 # or mysql:5.7
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 22222:80
volumes:
  data:
```

## Project structure

```
/data
  /database.sql
/wp-content
  /plugins
    [bunch of plugins]
  /themes
    [bunch of themes]
```

## `docker-compose up` output

```
docker-compose up
Starting wordpressstarter_wordpress_1
Starting wordpressstarter_db_1
Starting wordpressstarter_phpmyadmin_1
Attaching to wordpressstarter_phpmyadmin_1, wordpressstarter_wordpress_1, wordpressstarter_db_1
phpmyadmin_1  | 2017-02-13 22:32:46,188 CRIT Supervisor running as root (no user in config file)
phpmyadmin_1  | 2017-02-13 22:32:46,188 WARN Included extra file "/etc/supervisor.d/nginx.ini" during parsing
phpmyadmin_1  | 2017-02-13 22:32:46,188 WARN Included extra file "/etc/supervisor.d/php.ini" during parsing
wordpress_1   | ===============================================================================
wordpress_1   |                          Begin WordPress Installation
phpmyadmin_1  | Unlinking stale socket /run/supervisord.sock
phpmyadmin_1  | 2017-02-13 22:32:46,500 INFO RPC interface 'supervisor' initialized
phpmyadmin_1  | 2017-02-13 22:32:46,500 CRIT Server 'unix_http_server' running without any HTTP authentication checking
phpmyadmin_1  | 2017-02-13 22:32:46,500 INFO supervisord started with pid 1
wordpress_1   | ===============================================================================
wordpress_1   | ==> Waiting for MySQL to initialize...
phpmyadmin_1  | 2017-02-13 22:32:47,503 INFO spawned: 'php-fpm' with pid 15
phpmyadmin_1  | 2017-02-13 22:32:47,506 INFO spawned: 'nginx' with pid 16
db_1          | 2017-02-13 22:32:47 140177790310336 [Note] mysqld (mysqld 10.1.20-MariaDB-1~jessie) starting as process 1 ...
db_1          | 2017-02-13 22:32:47 140177790310336 [Note] InnoDB: Using mutexes to ref count buffer pool pages
db_1          | 2017-02-13 22:32:47 140177790310336 [Note] InnoDB: The InnoDB memory heap is disabled
db_1          | 2017-02-13 22:32:47 140177790310336 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
db_1          | 2017-02-13 22:32:47 140177790310336 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
db_1          | 2017-02-13 22:32:47 140177790310336 [Note] InnoDB: Compressed tables use zlib 1.2.8
db_1          | 2017-02-13 22:32:47 140177790310336 [Note] InnoDB: Using Linux native AIO
db_1          | 2017-02-13 22:32:47 140177790310336 [Note] InnoDB: Using SSE crc32 instructions
db_1          | 2017-02-13 22:32:47 140177790310336 [Note] InnoDB: Initializing buffer pool, size = 256.0M
db_1          | 2017-02-13 22:32:47 140177790310336 [Note] InnoDB: Completed initialization of buffer pool
db_1          | 2017-02-13 22:32:47 140177790310336 [Note] InnoDB: Highest supported file format is Barracuda.
db_1          | 2017-02-13 22:32:47 140177790310336 [Note] InnoDB: The log sequence numbers 4411345 and 4411345 in ibdata files do not match the log sequence number 5324244 in the ib_logfiles!
db_1          | 2017-02-13 22:32:47 140177790310336 [Note] InnoDB: Database was not shutdown normally!
db_1          | 2017-02-13 22:32:47 140177790310336 [Note] InnoDB: Starting crash recovery.
db_1          | 2017-02-13 22:32:47 140177790310336 [Note] InnoDB: Reading tablespace information from the .ibd files...
db_1          | 2017-02-13 22:32:47 140177790310336 [Note] InnoDB: Restoring possible half-written data pages 
db_1          | 2017-02-13 22:32:47 140177790310336 [Note] InnoDB: from the doublewrite buffer...
db_1          | 2017-02-13 22:32:48 140177790310336 [Note] InnoDB: 128 rollback segment(s) are active.
db_1          | 2017-02-13 22:32:48 140177790310336 [Note] InnoDB: Waiting for purge to start
db_1          | 2017-02-13 22:32:48 140177790310336 [Note] InnoDB:  Percona XtraDB (http://www.percona.com) 5.6.34-79.1 started; log sequence number 5324244
db_1          | 2017-02-13 22:32:48 140177003484928 [Note] InnoDB: Dumping buffer pool(s) not yet started
db_1          | 2017-02-13 22:32:48 140177790310336 [Note] Plugin 'FEEDBACK' is disabled.
db_1          | 2017-02-13 22:32:48 140177790310336 [Note] Recovering after a crash using tc.log
db_1          | 2017-02-13 22:32:48 140177790310336 [Note] Starting crash recovery...
db_1          | 2017-02-13 22:32:48 140177790310336 [Note] Crash recovery finished.
db_1          | 2017-02-13 22:32:48 140177790310336 [Note] Server socket created on IP: '::'.
db_1          | 2017-02-13 22:32:48 140177790310336 [Warning] 'proxies_priv' entry '@% root@3bd8674a4599' ignored in --skip-name-resolve mode.
db_1          | 2017-02-13 22:32:48 140177790310336 [Note] mysqld: ready for connections.
db_1          | Version: '10.1.20-MariaDB-1~jessie'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
phpmyadmin_1  | 2017-02-13 22:32:48,521 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
phpmyadmin_1  | 2017-02-13 22:32:48,521 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
wordpress_1   |   ->  mysqld is alive
wordpress_1   | ==> Configuring WordPress
wordpress_1   |   -> Generating wp-config.php file... ✓
wordpress_1   | ==> Checking database
wordpress_1   |   -> Database exists. SKIPPING... 
wordpress_1   | ==> Checking for multisite
wordpress_1   |   -> Multisite not found. SKIPPING... 
wordpress_1   | ==> Checking themes
wordpress_1   |   -> No theme dependencies listed 
wordpress_1   | ==> Checking for orphaned themes
wordpress_1   |   -> 'Divi' no longer needed. Pruning ✓
wordpress_1   |   -> 'craftyblog' no longer needed. Pruning ✓
wordpress_1   |   -> 'dailyjournal' no longer needed. Pruning ✓
wordpress_1   |   -> 'emulsion' no longer needed. Pruning ✓
wordpress_1   |   -> 'mt-agency' no longer needed. Pruning ✓
wordpress_1   |   -> 'mt-exhibit' no longer needed. Pruning ✓
wordpress_1   |   -> 'mt-maker' no longer needed. Pruning ✓
wordpress_1   |   -> 'portfolio' no longer needed. Pruning ✓
wordpress_1   |   -> 'twentyfifteen' no longer needed. Pruning ✓
wordpress_1   |   -> 'twentyfourteen' no longer needed. Pruning ✓
wordpress_1   |   -> 'twentysixteen' no longer needed. Pruning ✓
wordpress_1   |   -> 'twentythirteen' no longer needed. Pruning ✓
wordpress_1   |   -> 'uw-oshkosh-divi' no longer needed. Pruning Error: No themes deleted.
wordpress_1   | ✘
wordpress_1   | ==> Checking plugins
wordpress_1   |   -> No plugin dependencies listed 
wordpress_1   | ==> Checking for orphaned plugins
wordpress_1   |   -> 'mt-mail' no longer needed. Pruning... ✓
wordpress_1   |   -> 'mt-system-plugin' no longer needed. Pruning... ✓
wordpress_1   |   -> '404-to-301' no longer needed. Pruning... ✓
wordpress_1   |   -> 'adminimize' no longer needed. Pruning... Fatal error: Cannot redeclare _mw_adminimize_import_json() (previously declared in /app/wp-content/plugins/adminimize/adminimize.php:1755) in /app/wp-content/plugins/adminimize/adminimize.php on line 1755
wordpress_1   | ✘
wordpress_1   |   -> 'akismet' no longer needed. Pruning... ✓
wordpress_1   |   -> 'elegant-themes-updater' no longer needed. Pruning... ✓
wordpress_1   |   -> 'ewww-image-optimizer' no longer needed. Pruning... Fatal error: Cannot redeclare ewww_image_optimizer_remove_binaries() (previously declared in /app/wp-content/plugins/ewww-image-optimizer/ewww-image-optimizer.php:2326) in /app/wp-content/plugins/ewww-image-optimizer/ewww-image-optimizer.php on line 2326
wordpress_1   | ✘
wordpress_1   |   -> 'font-awesome-shortcodes' no longer needed. Pruning... ✓
wordpress_1   |   -> 'gravityforms' no longer needed. Pruning... ✓
wordpress_1   |   -> 'html-javascript-adder' no longer needed. Pruning... ✓
wordpress_1   |   -> 'json-content-importer' no longer needed. Pruning... ✓
wordpress_1   |   -> 'sidekick' no longer needed. Pruning... ✓
wordpress_1   |   -> 'mt-gd-site-stager' no longer needed. Pruning... ✓
wordpress_1   |   -> 'tablepress' no longer needed. Pruning... ✓
wordpress_1   |   -> 'wordpress-importer' no longer needed. Pruning... ✓
wordpress_1   |   -> 'wp101-video-tutorial' no longer needed. Pruning... ✓
wordpress_1   |   -> 'wp-simple-anchors-links' no longer needed. Pruning... ✓
wordpress_1   |   -> 'wordpress-seo' no longer needed. Pruning... ✓
wordpress_1   | ==> Finalizing
wordpress_1   |   -> .htaccess exists. SKIPPING... 
wordpress_1   |   -> Adjusting file permissions ✓
wordpress_1   | ===============================================================================
wordpress_1   |                        WordPress Configuration Complete!
wordpress_1   | ===============================================================================
wordpress_1   | [Mon Feb 13 22:33:28.251430 2017] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.10 (Debian) PHP/7.0.14 configured -- resuming normal operations
wordpress_1   | [Mon Feb 13 22:33:28.251484 2017] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
```

**Comment by dsifford** [comment]
Hi @musicaljoeker 

To prevent your `local` themes and plugins from being pruned, all you need to do is list them explicitly in `PLUGINS` and `THEMES` and prefix them with a `[local]` tag...

So, in your case... Your compose file should look like this...

```yml
version: '2'
services:
  wordpress:
    image: visiblevc/wordpress:latest
    ports:
      - 8080:80
    volumes:
      - ./data:/data
      - ./wp-content/themes:/app/wp-content/themes
      - ./wp-content/plugins:/app/wp-content/plugins
      - ./wp-content/uploads:/app/wp-content/uploads
    environment:
      DB_NAME: wordpress
      DB_PASS: root
      PLUGINS: >-
        [local]mt-mail,
        [local]mt-system-plugin
        # ...etc
      THEMES: >-
        [local]Divi
        # ...etc
  db:
    image: mariadb:10 # or mysql:5.7
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 22222:80
volumes:
  data:
```

As a side note: I'm curious why you have all of those plugins and themes installed locally in the first place? Installing them fresh on each build helps ensure that your entire team's working copy is identical  and also it minimizes usage of disk space. Unless the plugins or themes are ones that are paid for, I'd recommend definitely installing them using Docker, rather than using a volume.

Hope that helps.
